### ISSUE TITLE
艦これ 2016 E2 水無月ハイエース作戦

### ISSUE THREAD

**Issue by TomoyaShibata** [TomoyaShibata/zatsu#4]
## Description

水無月ハイエース作戦を敢行する。
### 艦隊編成
- 大淀（パンチ）
- 利根改二（殴りながら制空）
- 江風改二（大発）
- 夕雲（ハネムーン）
- 如月改二（大発）
- 瑞穂（制空、甲標的）
## Reference

<blockquote class="twitter-tweet" data-lang="en"><p lang="ja" dir="ltr">対潜警戒の観点から s/皐月/照月 にしてみたがうーん。 <a href="https://t.co/8itYue8N8z">pic.twitter.com/8itYue8N8z</a></p>&mdash; バトルプログラマー柴田智也 (@tomoya_shibata) <a href="https://twitter.com/tomoya_shibata/status/764253693524836352">August 13, 2016</a></blockquote>

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

→ 調査結果 E2 攻略に適さない布陣だったので本 Issue にて上書き。

**Comment by TomoyaShibata** [comment]
s/予備大淀/大淀

E3 で出番がないのでとくに予備を出す必要が無かった。

**Comment by Grabacr07** [comment]
E-2 とはいえドロップがそこそこ良いので、あえて輸送力を落とし戦力を投入することで S 勝利回数を稼ぎ、ゲージ削りと掘りを両立するという作戦も一考の余地があります。

**Comment by TomoyaShibata** [comment]
> E-2 とはいえドロップがそこそこ良いので、あえて輸送力を落とし戦力を投入することで S 勝利回数を上げ、ゲージ削りと掘りを両立する作戦も一考の余地があります。

なるほど？
とりあえず駆逐艦3隻に3つの大発は配給が足りない大問題が発覚したためハネムーン公開として睦月 out 夕雲で彼我の戦力を見定めてみます。

**Comment by TomoyaShibata** [comment]
s/睦月改二/夕雲

**Comment by TomoyaShibata** [comment]
![kancolle-160815-22533409](https://cloud.githubusercontent.com/assets/2193123/17666505/6eae200a-633b-11e6-94f5-b4b217ceec6d.png)

ハイエース作戦成功したため Issue クローズします。

## ボス S 勝利時 Drop 情報
- 高雄 
- 夕張 
- 飛鷹 
- 飛鷹 
- 鳳翔

以上。
